CC=g++
CFLAGS=-Wall -g -std=c++14 -fPIC
DYFLAGS=-shared
DEPS=-lcrypto -lssl -lstdc++ -lboost_system -lboost_filesystem -lboost_date_time -lboost_chrono

TARGET = libsign.so
 
SRCS := $(wildcard *.cpp)  
 
OBJS := $(patsubst %cpp, %o, $(SRCS))  
 
all: $(TARGET)  
 
$(TARGET): $(OBJS)  
	$(CC) $(CFLAGS) $(DEPS) $(DYFLAGS) -o $@ $^
%.o:%.cpp
	$(CC) $(CFLAGS) -c $<
 
clean:  
	rm -f *.o $(TARGET)
